import {
  ACCOUNT_USER_RESOURCE_ACCOUNT_MY_ACCOUNT,
  ACCOUNT_USER_RESOURCE_ACCOUNT_MY_SHOP,
  ACCOUNT_USER_RESOURCE_ACCOUNT_SHOPS,
  ACCOUNT_USER_RESOURCE_ACCOUNT_USERS,
  ACCOUNT_USER_RESOURCE_CATALOG,
  ACCOUNT_USER_RESOURCE_CONTENT_BLOG,
  ACCOUNT_USER_RESOURCE_CONTENT_CONTENT,
  ACCOUNT_USER_RESOURCE_CONTENT_PAGES,
  ACCOUNT_USER_RESOURCE_MARKETING_ADVANTAGE,
  ACCOUNT_USER_RESOURCE_MARKETING_COMMUNICATION,
  ACCOUNT_USER_RESOURCE_MARKETING_EXPORT,
  ACCOUNT_USER_RESOURCE_MARKETING_REVIEWS,
  ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_CUSTOMERS,
  ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_ORDERS,
  ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_STATS,
  ACCOUNT_USER_RESOURCE_SETTINGS_SHOP,
  ACCOUNT_USER_RESOURCE_SETTINGS_SKIN,
  ACCOUNT_USER_RESOURCE_SETTINGS_SYSTEM,
} from '../account-user-resource';


export type AccountRoleType =
  'admin'
  | 'in_charge'
  | 'editor'
  | 'logistician'
  | 'marketing_manager'
  | 'designer'
  | 'custom';

export interface AccountUserBaseModel {
  value: AccountRoleType;
  resources: AccountUserResourceBaseModel;
}

export interface AccountUserResourceBaseModel {
  [ACCOUNT_USER_RESOURCE_CATALOG]: boolean;
  [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_ORDERS]: boolean;
  [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_CUSTOMERS]: boolean;
  [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_STATS]: boolean;
  [ACCOUNT_USER_RESOURCE_MARKETING_ADVANTAGE]: boolean;
  [ACCOUNT_USER_RESOURCE_MARKETING_COMMUNICATION]: boolean;
  [ACCOUNT_USER_RESOURCE_MARKETING_EXPORT]: boolean;
  [ACCOUNT_USER_RESOURCE_MARKETING_REVIEWS]: boolean;
  [ACCOUNT_USER_RESOURCE_CONTENT_CONTENT]: boolean;
  [ACCOUNT_USER_RESOURCE_CONTENT_PAGES]: boolean;
  [ACCOUNT_USER_RESOURCE_CONTENT_BLOG]: boolean;
  [ACCOUNT_USER_RESOURCE_SETTINGS_SKIN]: boolean;
  [ACCOUNT_USER_RESOURCE_SETTINGS_SHOP]: boolean;
  [ACCOUNT_USER_RESOURCE_SETTINGS_SYSTEM]: boolean;
  [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_ACCOUNT]: boolean;
  [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_SHOP]: boolean;
  [ACCOUNT_USER_RESOURCE_ACCOUNT_SHOPS]: boolean;
  [ACCOUNT_USER_RESOURCE_ACCOUNT_USERS]: boolean;
}

export const AccountUserRoleAdminModel: AccountUserBaseModel = {
  value: 'admin',
  resources: {
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_ACCOUNT]: true,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_SHOP]: true,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_SHOPS]: true,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_USERS]: true,
    [ACCOUNT_USER_RESOURCE_CATALOG]: true,
    [ACCOUNT_USER_RESOURCE_CONTENT_BLOG]: true,
    [ACCOUNT_USER_RESOURCE_CONTENT_CONTENT]: true,
    [ACCOUNT_USER_RESOURCE_CONTENT_PAGES]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_ADVANTAGE]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_COMMUNICATION]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_EXPORT]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_REVIEWS]: true,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_CUSTOMERS]: true,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_ORDERS]: true,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_STATS]: true,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SHOP]: true,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SKIN]: true,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SYSTEM]: true,
  }
};

export const AccountUserRoleInChargeModel: AccountUserBaseModel = {
  value: 'in_charge',
  resources: {
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_ACCOUNT]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_SHOPS]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_USERS]: false,
    [ACCOUNT_USER_RESOURCE_CATALOG]: true,
    [ACCOUNT_USER_RESOURCE_CONTENT_BLOG]: true,
    [ACCOUNT_USER_RESOURCE_CONTENT_CONTENT]: true,
    [ACCOUNT_USER_RESOURCE_CONTENT_PAGES]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_ADVANTAGE]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_COMMUNICATION]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_EXPORT]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_REVIEWS]: true,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_CUSTOMERS]: true,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_ORDERS]: true,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_STATS]: true,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SHOP]: true,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SKIN]: true,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SYSTEM]: true,
  }
};

export const AccountUserRoleEditorModel: AccountUserBaseModel = {
  value: 'editor',
  resources: {
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_ACCOUNT]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_SHOPS]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_USERS]: false,
    [ACCOUNT_USER_RESOURCE_CATALOG]: true,
    [ACCOUNT_USER_RESOURCE_CONTENT_BLOG]: true,
    [ACCOUNT_USER_RESOURCE_CONTENT_CONTENT]: true,
    [ACCOUNT_USER_RESOURCE_CONTENT_PAGES]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_ADVANTAGE]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_COMMUNICATION]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_EXPORT]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_REVIEWS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_CUSTOMERS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_ORDERS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_STATS]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SKIN]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SYSTEM]: false,
  }
};

export const AccountUserRoleLogisticianModel: AccountUserBaseModel = {
  value: 'logistician',
  resources: {
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_ACCOUNT]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_SHOPS]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_USERS]: false,
    [ACCOUNT_USER_RESOURCE_CATALOG]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_BLOG]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_CONTENT]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_PAGES]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_ADVANTAGE]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_COMMUNICATION]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_EXPORT]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_REVIEWS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_CUSTOMERS]: true,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_ORDERS]: true,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_STATS]: true,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SKIN]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SYSTEM]: false,
  }
};

export const AccountUserRoleMarketingManagerModel: AccountUserBaseModel = {
  value: 'marketing_manager',
  resources: {
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_ACCOUNT]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_SHOPS]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_USERS]: false,
    [ACCOUNT_USER_RESOURCE_CATALOG]: true,
    [ACCOUNT_USER_RESOURCE_CONTENT_BLOG]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_CONTENT]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_PAGES]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_ADVANTAGE]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_COMMUNICATION]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_EXPORT]: true,
    [ACCOUNT_USER_RESOURCE_MARKETING_REVIEWS]: true,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_CUSTOMERS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_ORDERS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_STATS]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SKIN]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SYSTEM]: false,
  }
};

export const AccountUserRoleDesignerModel: AccountUserBaseModel = {
  value: 'designer',
  resources: {
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_ACCOUNT]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_SHOPS]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_USERS]: false,
    [ACCOUNT_USER_RESOURCE_CATALOG]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_BLOG]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_CONTENT]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_PAGES]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_ADVANTAGE]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_COMMUNICATION]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_EXPORT]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_REVIEWS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_CUSTOMERS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_ORDERS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_STATS]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SKIN]: true,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SYSTEM]: false,
  }
};

export const AccountUserRoleCustomModel: AccountUserBaseModel = {
  value: 'custom',
  resources: {
    [ACCOUNT_USER_RESOURCE_CATALOG]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_ORDERS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_CUSTOMERS]: false,
    [ACCOUNT_USER_RESOURCE_ORDERS_AND_STATS_STATS]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_ADVANTAGE]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_COMMUNICATION]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_EXPORT]: false,
    [ACCOUNT_USER_RESOURCE_MARKETING_REVIEWS]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_CONTENT]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_PAGES]: false,
    [ACCOUNT_USER_RESOURCE_CONTENT_BLOG]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SKIN]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_SETTINGS_SYSTEM]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_ACCOUNT]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_MY_SHOP]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_SHOPS]: false,
    [ACCOUNT_USER_RESOURCE_ACCOUNT_USERS]: false,
  }
};























